autoscale=false
nofpsgage=true
darksub=false

quality=100

[image]
key=dm00disp

[dark]
key=dm00disp00

[satMask]
key=dm00dispST

[indi]
ipAddress=127.0.0.1
port=7624

[dm]
name=dmkilo
rhDevice=rhkilo

[north]
enabled=false

