# set function parameters
# string LOOPNUMBER will be replaced by loop number
# string DMINDEX will be replaced by DM index

setval DMch2disp-DMINDEX.procinfo.RTprio 49
#setval DMch2disp-DMINDEX.procinfo.cset dm00comb
#setval DMch2disp-DMINDEX.procinfo.taskset 39
setval DMch2disp-DMINDEX.AveMode 0
setval DMch2disp-DMINDEX.option.voltmode OFF
setval DMch2disp-DMINDEX.option.DClevel 0.0
setval DMch2disp-DMINDEX.astrogrid.sname aol0_DMastrogrid
setval DMch2disp-DMINDEX.astrogrid.mult 0.0


setval mlat-LOOPNUMBER.NBiter 200
setval mlat-LOOPNUMBER.wfsNBframemax 20
#setval mlat-LOOPNUMBER.procinfo.cset mlat
#setval mlat-LOOPNUMBER.procinfo.taskset 48

setval acquWFS-LOOPNUMBER.procinfo.RTprio 49
#setval acquWFS-LOOPNUMBER.procinfo.cset acqu_mvm
#setval acquWFS-LOOPNUMBER.procinfo.taskset 45
setval acquWFS-LOOPNUMBER.procinfo.loopcntMax -1
setval acquWFS-LOOPNUMBER.WFSnormfloor 1.0
setval acquWFS-LOOPNUMBER.comp.WFSsigav OFF
setval acquWFS-LOOPNUMBER.comp.WFSrefc OFF

setval wfs2cmodeval-LOOPNUMBER.procinfo.RTprio 48
#setval wfs2cmodeval-LOOPNUMBER.procinfo.cset acqu_mvm
#setval wfs2cmodeval-LOOPNUMBER.procinfo.taskset 45
setval wfs2cmodeval-LOOPNUMBER.GPUindex 0
setval wfs2cmodeval-LOOPNUMBER.option.MODENORM ON
setval wfs2cmodeval-LOOPNUMBER.inmasksname aol1_wfsmask

setval mfilt-LOOPNUMBER.procinfo.RTprio 48
#setval mfilt-LOOPNUMBER.procinfo.cset mfilt
#setval mfilt-LOOPNUMBER.procinfo.taskset 46
setval mfilt-LOOPNUMBER.AOloopindex LOOPNUMBER
setval mfilt-LOOPNUMBER.inmval aolLOOPNUMBER_modevalWFS
setval mfilt-LOOPNUMBER.procinfo.triggersname aolLOOPNUMBER_modevalWFS
setval mfilt-LOOPNUMBER.selfRM.NBmode 2400
setval mfilt-LOOPNUMBER.selfRM.zsize 6

setval mvalC2dm-LOOPNUMBER.procinfo.RTprio 48
#setval mvalC2dm-LOOPNUMBER.procinfo.cset acqu_mvm
#setval mvalC2dm-LOOPNUMBER.procinfo.taskset 45
setval mvalC2dm-LOOPNUMBER.GPUindex 99
